AsciiIdentifiers:
  Enabled: false

AsciiComments:
  Enabled: false

AccessorMethodName:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

LineLength:
  Max: 99

AllCops:
  Excludes:
    - 'Guardfile'
