AsciiIdentifiers:
  Enabled: false

AsciiComments:
  Enabled: false

AccessorMethodName:
  Enabled: false

# Nested modules should be 'nested'
# Nested classes should be 'nested'
# classes within nested modules should be 'compact'
ClassAndModuleChildren:
  Enabled: false
  EnforcedStyle: compact

LineLength:
  Max: 99

AllCops:
  Excludes:
    - 'Guardfile'
