language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby-19mode
  - rbx-2

bundler_args: -j4 --without development

script:
  - bundle exec rspec

addons:
  code_climate:
    repo_token: 4f9c56a5c9a2e99acd8e8f06491940f9174c6fd1e22236539bb2cbc2fefd0e30
