language: ruby

sudo: false

rvm:
  - 2.0.0
  - 2.1
  - 2.2.3
  - ruby-head
  - rbx
  - jruby-head

script:
  - bundle exec rspec

addons:
  code_climate:
    repo_token: 4f9c56a5c9a2e99acd8e8f06491940f9174c6fd1e22236539bb2cbc2fefd0e30
