version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: run tests
          command: |
            bundle exec rspec --format progress \
                            --out /tmp/test-results/rspec.xml \
                            --format progress

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
