require_relative 'emojidex/data/emoji'
require_relative 'emojidex/data/collection_checker'
require_relative 'emojidex/data/collection'
require_relative 'emojidex/data/utf'
require_relative 'emojidex/data/extended'
require_relative 'emojidex/data/category'
require_relative 'emojidex/data/categories'
